
--| Copyright (c) 1993-2006 University of Southern California and contributors.
--| All rights reserved.
--| Your use of this work is governed under the terms of the GNU General
--| Public License version 2.

-- This is a test control file

test_name 	eval-precondition-on-retry
test_description A routine `try' which has a precondition calls another routine `try2' which raises an exception.  If the calling routine catches the exception and retries, the precondition is evaluated again if code is melted.  Frozen code works correctly - it does not re-evaluate the precondition in the routine which catches the exception.

copy_sub 	Ace $TEST Ace
copy_raw 	test.e $CLUSTER test.e
compile_melted
compile_result 	ok

execute_work 	NONE 	exec_output1
execute_result 	ok
compare		exec_output1 output

compile_frozen
compile_result 	ok

c_compile_work
c_compile_result ok

execute_work 	NONE 	exec_output2
execute_result 	ok
compare		exec_output2 output

test_end
