
--| Copyright (c) 1993-2006 University of Southern California and contributors.
--| All rights reserved.
--| Your use of this work is governed under the terms of the GNU General
--| Public License version 2.

-- This is a test control file

test_name 	 deep-exception-in-rescue
test_description A class has a recursive routine `f' which at the depths of its recursion calls a routine `weasel' which raises an exception.  Routine `weasel' has a rescue clause which first calls `f' and then retries and succeeds.  When the system is executed, it dies with a panic (segmentation fault) if the depth of "exception in rescue clause" nesting is greater than 256.

copy_sub 	 Ace $TEST Ace
copy_raw 	 test.e  $CLUSTER test.e
compile_melted
compile_result 	 ok

execute_work	 NONE exec_output1 0 257
execute_result	 ok
compare		 exec_output1 output

execute_work	 NONE exec_output1 100 257
execute_result	 ok
compare		 exec_output1 output

execute_work	 NONE exec_output1 0 513	
execute_result	 ok
compare		 exec_output1 output

execute_work	 NONE exec_output1 100 513
execute_result	 ok
compare		 exec_output1 output

test_end
